_articles = [
    { id: 0, name: "1Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '01-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 1, name: "2Alien Worlds - Farmea TLM", ad: 1, status: 1, date: '02-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 2, name: "3Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '03-04-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 3, name: "4Alien Worlds - Farmea TLM", ad: 2, status: 1, date: '04-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 1 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 0, name: "5Alien Worlds - Farmea TLM", ad: 0, status: 0, date: '05-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 1, name: "6Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '06-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 2, name: "7Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '17-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 3, name: "8Alien Worlds - Farmea TLM", ad: 0, status: 0, date: '16-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 1 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 0, name: "9Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '15-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 1, name: "10Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '14-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 2, name: "11Alien Worlds - Farmea TLM", ad: 0, status: 1, date: '13-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 0 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'},
    { id: 3, name: "12Alien Worlds - Farmea TLM", ad: 3, status: 1, date: '12-05-2021', score: 4.5, url: "#", image: "https://s2.coinmarketcap.com/static/img/coins/200x200/9119.png", price: "Gratis", category_id: 1 , intro_description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel', description: 'Wisi forensibus mnesarchum in cum. Per id impetus abhorreant, his no <b>magna</b> definiebas, inani rationibus in quo. Ut vidisse dolores est, ut quis nominavi mel'}
];
_categories = [
    { id: 0, name: "Gratis", url: "#" },
    { id: 1, name: "Juegos", url: "#" },
    { id: 2, name: "Oportunidades", url: "#" },
    { id: 3, name: "Droplets", url: "#" }
];

